apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owasp-pvc
  namespace: owasp-zap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
