apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap
  namespace: owasp-zap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zap
  template:
    metadata:
      labels:
        app: zap
    spec:
      containers:
      - name: zap
        image: ghcr.io/zaproxy/zaproxy:stable
        ports:
        - containerPort: 8080
        - containerPort: 8090
        command: ["/bin/sh", "-c"]
        args: ["zap-webswing.sh -daemon -host 0.0.0.0 -port 8080 -webswing.port 8090; tail -f /dev/null"]
        resources:
          limits:
            cpu: "2"          # Increase CPU limit
            memory: "2Gi"     # Increase memory limit
          requests:
            cpu: "1"          # Increase CPU request
            memory: "1Gi"     # Increase memory request
