apiVersion: batch/v1
kind: CronJob
metadata:
  name: zap-scan
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: zap-scan
            image: ghcr.io/zaproxy/zaproxy:stable
            command:
            - /bin/sh
            - -c
            - while read domain; do zap-baseline.py -t "$domain" -r "/zap/zap_report_$(echo $domain | sed 's/[:\/]/_/g').html"; done < /zap/domains.txt
            volumeMounts:
            - name: zap-data
              mountPath: /zap
            - name: zap-domains
              mountPath: /zap/domains.txt
              subPath: domains.txt
          restartPolicy: OnFailure
          volumes:
          - name: zap-data
            emptyDir: {}
          - name: zap-domains
            configMap:
              name: zap-domains
